# Generated by Django 4.1.4 on 2023-03-12 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('socialweb', '0006_alter_post_options_comments_likes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
    ]
